//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerCFG.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerCFG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Run the program as Administrator.
        /// </summary>
        public static string Admin_Reserved {
            get {
                return ResourceManager.GetString("Admin Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap battery_charged {
            get {
                object obj = ResourceManager.GetObject("battery-charged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to cancel the Battery Report?.
        /// </summary>
        public static string Battery_Report {
            get {
                return ResourceManager.GetString("Battery Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Value {0}.
        /// </summary>
        public static string Default_Value {
            get {
                return ResourceManager.GetString("Default Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the schema &apos;{0}&apos;?.
        /// </summary>
        public static string Do_you_want_to_delete_the_schema {
            get {
                return ResourceManager.GetString("Do you want to delete the schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to duplicate the schema &apos;{0}&apos;?.
        /// </summary>
        public static string Do_you_want_to_duplicate_the_schema {
            get {
                return ResourceManager.GetString("Do you want to duplicate the schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to cancel the Energy Report?.
        /// </summary>
        public static string Energy_Report {
            get {
                return ResourceManager.GetString("Energy Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This report takes at least 60 seconds..
        /// </summary>
        public static string Energy_Report_Message {
            get {
                return ResourceManager.GetString("Energy Report Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Scheme.
        /// </summary>
        public static string New_Scheme_Name {
            get {
                return ResourceManager.GetString("New Scheme Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On AC Power.
        /// </summary>
        public static string On_AC_Power {
            get {
                return ResourceManager.GetString("On AC Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On battery.
        /// </summary>
        public static string On_battery {
            get {
                return ResourceManager.GetString("On battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste into Excel.
        /// </summary>
        public static string Paste_into_Excel {
            get {
                return ResourceManager.GetString("Paste into Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap power_icon {
            get {
                object obj = ResourceManager.GetObject("power-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to cancel the Power Report?.
        /// </summary>
        public static string Power_Report {
            get {
                return ResourceManager.GetString("Power Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon project {
            get {
                object obj = ResourceManager.GetObject("project", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From {0} to {1} step {2}  {3}.
        /// </summary>
        public static string RangeFromToIncrement {
            get {
                return ResourceManager.GetString("RangeFromToIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report Cancelled.
        /// </summary>
        public static string Report_Cancelled {
            get {
                return ResourceManager.GetString("Report Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore to {0}.
        /// </summary>
        public static string Restore_to {
            get {
                return ResourceManager.GetString("Restore to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving Power Scheme.
        /// </summary>
        public static string Saving_Power_Scheme {
            get {
                return ResourceManager.GetString("Saving Power Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Status_battery_charging {
            get {
                object obj = ResourceManager.GetObject("Status-battery-charging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
